spring.application.name=travelworkertimesheetexpenseclaimmanagementsystem
spring.datasource.url=jdbc:mysql://localhost:3306/travelworker
spring.datasource.username=root
spring.datasource.password=Faku-478088
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Suppress open-in-view warning
spring.jpa.open-in-view=false

# Reduce Hibernate/Spring noise
logging.level.org.hibernate=WARN
logging.level.org.springframework.data=WARN
logging.level.com.zaxxer.hikari=WARN