package com.twtecms.travelworkertimesheetexpenseclaimmanagementsystem.entity;

import jakarta.persistence.*;

import java.util.Date;

@Entity
public class Payment {
    //properties of the payment entity
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long paymentId; // This will be autogenerated for the payments
    private Long claimId; // foreign key that will be used to map to claim entity
    private Date paymentDate; // The date which the payment was made
    private String reference; // A description of the reference for the payment
    private Boolean status;// flag to check if the payment was processed
    private String processedBy; // Describes or names the financial employee who approved the transaction

    public Long getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    public Long getClaimId() {
        return claimId;
    }

    public void setClaimId(Long claimId) {
        this.claimId = claimId;
    }

    public Date getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getProcessedBy() {
        return processedBy;
    }

    public void setProcessedBy(String processedBy) {
        this.processedBy = processedBy;
    }
}
