package com.twtecms.travelworkertimesheetexpenseclaimmanagementsystem.entity;

import jakarta.persistence.*;

import java.util.Date;

@Entity
public class Payment {
    //properties of the payment entity
    @Id
    private Long paymentId; // This will be autogenerated for the payments
    private Long claimId; // foreign key that will be used to map to claim entity
    private Date paymentDate; // The date which the payment was made
    private String reference; // A description of the reference for the payment
    private Boolean status;// flag to check if the payment was processed
    private String processedBy; // Describes or names the financial employee who approved the transaction

}
