package com.twtecms.travelworkertimesheetexpenseclaimmanagementsystem.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;

import java.util.Date;

@Entity
public class Timesheet {

    //properties for the timesheet entity
    @Id
    private Long  timesheetId; // this should be autogenerated
    private Long  userId;//This is a foreign key from the user entity
    private Date workDate; // represents the day that the employee worked
    private Date startTime; // The time which the employee commenced work on the specific day
    private Date endTime; // The time which the employee left the work premises on the specific day
    private Integer total_hours; // The number of hours that the employee worked during the day
    private String location; //The premises at which the employee worked on the day
    private String description; // Description of the tasks performed bu the employee for the day
    private Boolean status ; // flag for if the worker knocked off from work ;

}
