package com.twtecms.travelworkertimesheetexpenseclaimmanagementsystem.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Timesheet {

    //properties for the timesheet entity
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long  timesheetId; // this should be autogenerated
    private Long  userId;//This is a foreign key from the user entity
    private String workDate; // represents the day that the employee worked
    private String startTime; // The time which the employee commenced work on the specific day
    private String endTime; // The time which the employee left the work premises on the specific day
    private Double total_hours; // The number of hours that the employee worked during the day
    private String location; //The premises at which the employee worked on the day
    private String description; // Description of the tasks performed bu the employee for the day
    private Boolean status ; // flag for if the worker knocked off from work ;

    public Long getTimesheetId() {
        return timesheetId;
    }

    public void setTimesheetId(Long timesheetId) {
        this.timesheetId = timesheetId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getWorkDate() {
        return workDate;
    }

    public void setWorkDate(String workDate) {
        this.workDate = workDate;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public Double getTotal_hours() {
        return total_hours;
    }

    public void setTotal_hours(Double total_hours) {
        this.total_hours = total_hours;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }
}
